### PR TITLE
#9 Multiplication table added .

### PR DESCRIPTION
**Pull request by apmkush**
Is everything ok ? If not please guide me .

### CODE REVIEW

**Comment by karastoyanov** [comment]
Good job! I will merge the PR into `development` branch.

**Comment by apmkush** [comment]
Thanks , I'm beginner and want to start contribute in open source project .If you have any suggestion on how to find good first issue please help me .

**Comment by karastoyanov** [comment]
This repository is created to offer a training environment for everyone who would like to exercise. You can keep contributing to this repository, just follow the basic rules:

* :warning: Every Pull Request should be opened to the `development` branch. No PR's to `main` will be merged.
* You can keep adding new code, just be creative, write your own code and upload it to the repo. It would be a good practice to write informative commits, PR's title, bodies and to include comments inside your code to give details about it.  Just follow the structure and upload your files in the folder for the respective language. In case that you want to upload a bigger project, create a separte directory. Check again the [README](https://github.com/karastoyanov/linux-hobby-club/blob/main/README.md) file for more details.
* Periodically I will create new exercies and will upload them in [Issues](https://github.com/karastoyanov/linux-hobby-club/issues/new/choose). You can open a new issue with the respective task for yourself and follow the assignement to execute the task. When I create a new task I will create a notification, so be sure to give the repo a star to recevice the news. 
* Keep in mind that the original idea behind the repo is to work entirly on a Linux OS only with `git` commands inside bash terminal. It is not obligatory, but it a strongly recommened. Check the [wiki](https://github.com/karastoyanov/linux-hobby-club/wiki) for more info.
* If you have more questions, do not hesitate to contact me.

**Comment by apmkush** [comment]
Thank you very much, I will follow this

**Pull request merged**
